### ISSUE TITLE
getting error -panic: runtime error: slice bounds out of range [:9] with length 8

### ISSUE THREAD

**Issue by haril-github** [go-acme/lego#1353]
I have installed lego package on Ubuntu but when run sudo lego command I am getting below message  -

```
panic: runtime error: slice bounds out of range [:9] with length 8

goroutine 1 [running]:
github.com/miekg/dns.ClientConfigFromReader(0x10e1d80, 0xc0000ac028, 0x0, 0x0, 0xc0000ac028)
        github.com/miekg/dns/clientconfig.go:94 +0x8d1
github.com/miekg/dns.ClientConfigFromFile(0xeeb9f6, 0x10, 0x0, 0x0, 0x0)
        github.com/miekg/dns/clientconfig.go:29 +0xde
github.com/go-acme/lego/challenge/dns01.getNameservers(0xeeb9f6, 0x10, 0x16fd460, 0x2, 0x2, 0x0, 0x0, 0x27)
        github.com/go-acme/lego/challenge/dns01/nameserver.go:74 +0x39
github.com/go-acme/lego/challenge/dns01.init()
        github.com/go-acme/lego/challenge/dns01/nameserver.go:29 +0x7b
```

**Comment by ldez** [comment]
@haril-github could you provide a way to reproduce?

**Comment by haril-github** [comment]
I am installing lego version lego (3.2.0-1)

**Comment by ldez** [comment]
Could you use the latest version: v4.2.0

**Comment by haril-github** [comment]
It is working with updated version v4.2.0 .Thanks for help.
